# Generated by Django 5.0 on 2023-12-14 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiClinic', '0003_alter_doctor_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiClinic.patient'),
        ),
    ]
