# Generated by Django 5.0 on 2023-12-11 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiClinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='ranking',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
