# Generated by Django 5.0 on 2023-12-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiClinic', '0002_doctor_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='ranking',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
